# -*- coding: utf-8 -*-

BATCH_SIZE = "batch_size"
CHECKPOINT_FNAME = "checkpoint_fname"
DATASET = "dataset"
EPOCHS = "epochs"
IN_DIRNAME = "in_dirname"
IO = "io"
LAYERS = "layers"
LEARN_HDF5_DATASET_FNAME = "learn_hdf5_dataset_fname"
LOSS_FUNCTION = "loss_function"
LR_SCHEDULER = "lr_scheduler"
METHOD = "method"
MODEL = "model"
MOMENTUM = "momentum"
NAME = "name"
OPTIMIZER = "optimizer"
OUT_DIRNAME = "out_dirname"
PRECISION = "precision"
SCALAR_MAP = "scalar_map"
SUBJ_SPLIT_FNAME = "subj_split_fname"
TRAIN = "train"
TYPE = "type"
